In [11]:
import torch
import numpy as np

In [12]:
torch.__version__

'1.1.0'

In [13]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


Converting to tensor

In [14]:
x=torch.from_numpy(arr)

In [16]:
type(x)

torch.Tensor

Another method to convert to tensor

In [17]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

Making 2d tensor

In [18]:
arr2d=np.arange(0.0,12.0)
arr2d=arr2d.reshape(4,3)

In [19]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [21]:
x2=torch.from_numpy(arr2d)